version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:

      MYSQL_ROOT_PASSWORD: user
    ports:
      - "3303:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8084:8080"

volumes: 
  db: